import { describe, expect, it, vi } from "vitest";
import React from "react";
import { renderToStaticMarkup } from "react-dom/server";
import RootLayout, { metadata } from "./layout";

vi.mock("next/font/google", () => ({
  Geist: vi.fn(() => ({ variable: "geist-sans" })),
  Geist_Mono: vi.fn(() => ({ variable: "geist-mono" })),
}));

vi.mock("../providers/AppProvider", () => ({
  AppProvider: ({ children }: { children: React.ReactNode }) => <>{children}</>,
}));

describe("RootLayout", () => {
  it("renders the shell and exposes metadata", () => {
    const markup = renderToStaticMarkup(
      RootLayout({ children: <main>content</main> }),
    );

    expect(markup).toContain('lang="en"');
    expect(markup).toContain(
      'class="geist-sans geist-mono h-full antialiased"',
    );
    expect(markup).toContain("content");
    expect(metadata.title).toBe("Create Next App");
    expect(metadata.description).toBe("Generated by create next app");
  });
});
